Agroin4/Controllers/comments1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agroin4.Models;
using Microsoft.AspNet.Identity;

namespace Agroin4.Controllers
{
    [Authorize]
    public class comments1Controller : Controller
    {
        private webAppModel db = new webAppModel();
        [Authorize]

        public ActionResult message()
        {
            TempData["testmsg"] = "<script>alert('Request Denied ');</script>";
            return View();
        }
        [Authorize]

        public ActionResult SaveComments(int id, string commenty)
        {
            comment commentobj = new comment();
            commentobj.user_id = new Guid(User.Identity.GetUserId());
            commentobj.user_email = (User.Identity.GetUserName());
            commentobj.TimeOfPost = DateTime.Now;
            commentobj.article_id = id;
            commentobj.comment_text = commenty;
            db.comments.Add(commentobj);
            db.SaveChanges();
            //return RedirectToAction("index","comments1",new { id=Id });
            return Json(new { redirectUrl = "/articles/Details", Id = id }, JsonRequestBehavior.AllowGet);

        }


        //public ActionResult Reply(int? id)
        //{
        //    comment commentobj = new comment();
        //    commentobj.user_id = new Guid(User.Identity.GetUserId());
        //    return View(commentobj);
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Reply(comment model)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        model.TimeOfPost = DateTime.Now;
        //        db.comments.Add(model);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(model);
        //}
       [AllowAnonymous]
        // GET: comments1
        public ActionResult Index(int Id)
        {
            var comments = db.comments.OrderByDescending(p => p.TimeOfPost).Where(p => p.article_id == Id);//.Include(c => c.article).Include(c => c.Comment);
            return PartialView(comments.ToList());
        }
        [Authorize]
        // GET: comments1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comment comment = db.comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }
        [Authorize]

        // GET: comments1/Create
        public ActionResult Create(int id)
        {
            comment commentobj = new comment() { article_id = id };
            // ViewBag.article_id = new SelectList(db.articles, "id", "article_name");
            // ViewBag.parentComment = new SelectList(db.comments, "id", "comment_text");
            return PartialView(commentobj);
        }

        // POST: comments1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.user_id = new Guid(User.Identity.GetUserId());
                comment.user_email = (User.Identity.GetUserName());
                comment.TimeOfPost = DateTime.Now;

                db.comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.article_id = new SelectList(db.articles, "id", "article_name", comment.article_id);
            // ViewBag.parentComment = new SelectList(db.comments, "id", "comment_text", comment.parentComment);
            return View(comment);
        }
        [Authorize]
        // GET: comments1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comment comment = db.comments.Find(id);
            Guid current_id = new Guid(User.Identity.GetUserId());
            //Guid admin_id = new Guid("b4f9e79e-d000-481a-91dc-511e7f513b7a");

            if (current_id != comment.user_id)

            {
                return RedirectToAction("message");

            }
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.article_id = new SelectList(db.articles, "id", "article_name", comment.article_id);
            // ViewBag.parentComment = new SelectList(db.comments, "id", "comment_text", comment.parentComment);
            return View(comment);
        }

        // POST: comments1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "articles", new { id = comment.article_id });
            }
            ViewBag.article_id = new SelectList(db.articles, "id", "article_name", comment.article_id);
            //ViewBag.parentComment = new SelectList(db.comments, "id", "comment_text", comment.parentComment);
            return View(comment);
        }
        [Authorize]
        // GET: comments1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comment comment = db.comments.Find(id);
            Guid current_id = new Guid(User.Identity.GetUserId());
            //Guid admin_id = new Guid("b4f9e79e-d000-481a-91dc-511e7f513b7a");

            if (current_id != comment.user_id)

            {
                return RedirectToAction("message");

            }
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: comments1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            comment comment = db.comments.Find(id);
            db.comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Details","articles",new { id = comment.article_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Agroin4/Views/comments1/Create.cshtml
@model Agroin4.Models.comment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","comments1", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.user_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.TextAreaFor(model => model.comment_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("comment_text", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comment_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOfPost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOfPost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeOfPost, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.parentComment, "parentComment", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("parentComment", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.parentComment, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">

            <div class="col-md-10">

                @Html.HiddenFor(model => model.article_id)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Agroin4/Views/comments1/Delete.cshtml
@model Agroin4.Models.comment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.article.article_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.article.article_name)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Comment.comment_text)
        </dt>*@

        @*<dd>
            @Html.DisplayFor(model => model.Comment.comment_text)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.user_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_id)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.comment_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.comment_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeOfPost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOfPost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Agroin4/Views/comments1/Details.cshtml
@model Agroin4.Models.comment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.article.article_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.article.article_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment.comment_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment.comment_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.comment_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.comment_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeOfPost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeOfPost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Agroin4/Views/comments1/Edit.cshtml
@model Agroin4.Models.comment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.user_id)


        @*<div class="form-group">
            @Html.LabelFor(model => model.user_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.comment_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.comment_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comment_text, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.TimeOfPost)


        @*<div class="form-group">
            @Html.LabelFor(model => model.TimeOfPost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOfPost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeOfPost, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.parentComment, "parentComment", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("parentComment", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.parentComment, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.article_id, "article_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("article_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.article_id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Agroin4/Views/comments1/Index.cshtml
@using Agroin4.CustomHtmlHelpers
@model IEnumerable<Agroin4.Models.comment>

@{
    ViewBag.Title = "Index";
}
<div class="card">
    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Comments</h2>
    </div>

    @*<p>
            @Html.ActionLink("Create New", "Create")
        </p>*@
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.user_email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.comment_text)
            </th>


            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.user_email)
                </td>
                <td>
                    <div style="overflow:auto;word-wrap:hyphenate;text-align:justify;max-width:700px">
                        @Html.DisplayWithBreaksFor(modelItem => item.comment_text)
                    </div>
                   
                </td>


                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |

                    @Html.ActionLink("Delete", "Delete", new { id = item.id })



                </td>
            </tr>
        }

    </table>
</div>

Agroin4/Views/comments1/message.cshtml
@{
    ViewBag.Title = "Unsuccessful";
}



@if (TempData["testmsg"] != null)
{
    @Html.Raw(TempData["testmsg"])
}

    @*<div>
            @Html.ActionLink("Back ", "Index")
        </div>*@