Agroin4/Models/article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agroin4.Models
{
    public class article
    {
        public int id { get; set; }
        [Display(Name = "Article Name")]
        public string article_name { get; set; }
        [Display(Name = "Crop Name")]
        public int crop_id { get; set; }
        [Display(Name = "Published On")]
        public DateTime date_time { get; set; }
        public int rating { get; set; }
        public  Guid expert_id { get; set; }
        [Display(Name = "Email")]
        
        public string expert_email { get; set; }
        [Display(Name = "Article Description")]
        [DataType(DataType.MultilineText)]
        public string article_description { get; set; }

        //public virtual ICollection<comment> comments { get; set; }

    }
    
}

Agroin4/Controllers/articlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agroin4.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;

namespace Agroin4.Controllers
{
    public class articlesController : Controller
    {
        private webAppModel db = new webAppModel();
        //public ActionResult comment(int id)
        //{
        //    return RedirectToAction("create", "comments", new { Id = id });

        //}
        [AllowAnonymous]
        // GET: articles
        public ActionResult Index(int? id)
        {
            var articleobj = db.articles.Where(p => p.crop_id == id).ToList();
            return View(articleobj);
        }
        [AllowAnonymous]
        // GET: articles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            article article = db.articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }
        [Authorize(Roles = "Admin,Expert")]
        // GET: articles/Create
        public ActionResult Create()
        {
            ViewData["IdcropList"] = db.crops.Select(p => new SelectListItem() { Text = p.crop_name, Value = p.id.ToString() }).AsEnumerable();
            return PartialView();
        }

        // POST: articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( article article)
        {
            if (ModelState.IsValid)
            {
                article.expert_id = new Guid(User.Identity.GetUserId());
                article.expert_email =(User.Identity.GetUserName());
                article.date_time = DateTime.Now;
                db.articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index",new { id = article.crop_id });
            }

            return View(article);
        }
        public ActionResult message()
        {
            TempData["testmsg"] = "<script>alert('Request Denied ');</script>";
            return View();
        }
        [Authorize(Roles = "Admin,Expert")]

        // GET: articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            ViewData["IdcropList"] = db.crops.Select(p => new SelectListItem() { Text = p.crop_name, Value = p.id.ToString() }).AsEnumerable();
            article article = db.articles.Find(id);
            Guid current_id= new Guid(User.Identity.GetUserId());
            //Guid admin_id = new Guid("b4f9e79e-d000-481a-91dc-511e7f513b7a");

            if (current_id != article.expert_id)
                
            {
                return RedirectToAction("message" );

            }
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(article article)
        {
            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                //article.expert_email = (User.Identity.GetUserName());

                db.SaveChanges();
                return RedirectToAction("Index",new { id=article.crop_id});
            }
            return View(article);
        }

        [Authorize(Roles = "Admin,Expert")]

        // GET: articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            article article = db.articles.Find(id);
            Guid current_id = new Guid(User.Identity.GetUserId());
            //Guid admin_id = new Guid("b4f9e79e-d000-481a-91dc-511e7f513b7a");
            

            if (current_id != article.expert_id) /*||  !( Roles.GetRolesForUser().Contains("Admin") )  )*/

            {
                return RedirectToAction("message");

            }
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            article article = db.articles.Find(id);
            db.articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index",new { id = article.crop_id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Agroin4/Views/articles/Create.cshtml
@model Agroin4.Models.article

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm("Create","articles", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.article_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 p-b-10">
                @Html.EditorFor(model => model.article_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.article_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.crop_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 p-b-10">
                @Html.DropDownList("crop_id", ViewData["IdcropList"] as IEnumerable<SelectListItem>, "Select Crop", htmlAttributes: new { @class = "form-control" })

               
                @Html.ValidationMessageFor(model => model.crop_id, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.date_time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_time, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.expert_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.expert_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.expert_id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.article_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="panel col-md-10 p-b-10">
                @Html.TextArea("article_description", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.article_description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary pull-right" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

Agroin4/Views/articles/Delete.cshtml
@model Agroin4.Models.article

@{
    ViewBag.Title = "Delete";
}

@*<h2>Delete</h2>*@
<div class="card">
    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Are you sure you want to delete this article?</h2>
    </div>
    <div>
        @*<h4>article</h4>*@
        @*<hr />*@
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.article_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.article_name)
            </dd>

            @*<dt>
                    @Html.DisplayNameFor(model => model.crop_id)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.crop_id)
                </dd>*@

            <dt>
                @Html.DisplayNameFor(model => model.date_time)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.date_time)
            </dd>

            @*<dt>
                    @Html.DisplayNameFor(model => model.rating)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.rating)
                </dd>*@

            <dt>
                @Html.DisplayNameFor(model => model.expert_email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.expert_email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.article_description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.article_description)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Agroin4/Views/articles/Details.cshtml
@using Agroin4.CustomHtmlHelpers
@model Agroin4.Models.article


@{
    ViewBag.Title = "Details";
}
<div class="card">
    @*<h2>Details</h2>*@

    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Article Details</h2>
    </div>
    @*<hr />*@
    <dl class="dl-horizontal p-t-10">

        @Html.HiddenFor(m => m.id, new { id = "hiddenIdField" })


        <dt>
            @Html.DisplayNameFor(model => model.article_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.article_name)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.crop_id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.crop_id)
            </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.date_time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_time)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.rating)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.rating)
            </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.expert_email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.expert_email)
        </dd>
        <hr>
        <dt>
            @Html.DisplayNameFor(model => model.article_description)
        </dt>
        @*<br />*@
        <dd>
            <div style="overflow:auto;word-wrap:hyphenate;text-align:justify; max-width:700px">
                @Html.DisplayWithBreaksFor(model => model.article_description)
            </div>

        </dd>

    </dl>
</div>

@*<div>
        @Html.Partial("/comments1/index",new ViewDataDictionary { { "id",Model.id } })
    </div>*@
@*<div>
        @Html.ActionLink("comment","comment",new {id=Model.id })
    </div>*@
<div class="card">
    <br />
    <p>
        <div class="input-group">
            <span class="input-group-addon">Comment here</span>
            <input type="text" id="txtComments" class="form-control " placeholder="text" aria-describedby="basic-addon1">
        </div>
        <div class="col-md-offset-2">
            <button type="button" class="btn btn-primary" id="createComment">Comment</button>
            </div>
</p>
</div>
<div id="commentsection">
    @Html.Action("Index", "comments1", Model.id)
</div>
@section Scripts {
    <script>
    $("#createComment").on('click', function () {
        var model = { 'id': Id, 'comments': comments };
        var comments = $('#txtComments').val();
        var Id = $('#hiddenIdField').val();


        $.ajax({
            //your params as it is
            url: '/comments1/SaveComments',
            data: { 'id': Id, 'commenty': comments },
              type: 'post'
        }).done(function (response) {
            //window.location = redirectURl //for redirecting to article details page
            //if you are passing id as parameter to the redirected page then you can do something like this.
          // window.location = response.redirectUrl + '/' + response.Id;
            // window.location.href = 'Url.Action("details", "articles", new { id = "id1" })';

           $.ajax({
               url: '/comments1/Index?Id=' + response.Id,
               type:'GET'
           }).done(function(responsecomment) {
               $('#commentsection').html(responsecomment);
           }).fail(function(err) {
               alert("Error Occured : " + err);
           });
        }).fail(function (error) {

        });

        });
    </script>
}

Agroin4/Views/articles/Edit.cshtml
@model Agroin4.Models.article

@{
    ViewBag.Title = "Edit";
}

@*<h2>Edit</h2>*@
<div class="card">
    @*<h2>Details</h2>*@

    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Edit</h2>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal p-t-10">
            @*<h4>article</h4>
                <hr />*@
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.article_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 p-b-10">
                    @Html.EditorFor(model => model.article_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.article_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.crop_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 p-b-10">

                    @Html.DropDownList("crop_id", ViewData["IdcropList"] as IEnumerable<SelectListItem>, "Select Crop", htmlAttributes: new { @class = "form-control" })


                    @Html.ValidationMessageFor(model => model.crop_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.date_time, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 p-b-10">
                    @Html.EditorFor(model => model.date_time, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.date_time, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.rating, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 p-b-10">
                    @Html.EditorFor(model => model.rating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.rating, "", new { @class = "text-danger" })
                </div>
            </div>*@
            @Html.HiddenFor(model =>model.expert_id)
            @Html.HiddenFor(model => model.expert_email)


            @*<div class="form-group">
                @Html.LabelFor(model => model.expert_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 p-b-10">
                    @Html.EditorFor(model => model.expert_id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.expert_id, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.article_description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 p-b-10">
                    @Html.EditorFor(model => model.article_description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.article_description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Agroin4/Views/articles/Index.cshtml
@model IEnumerable<Agroin4.Models.article>

@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>*@
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<div class="card">
    
    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Index</h2>
    </div>
    <p>
        @*@Html.ActionLink("Create New", "Create",null,new { id="createArticle", @class="btn btn-primary" })*@
        <button type="button" class="btn btn-primary" id="createArticle"><span class="glyphicon glyphicon-plus"></span></button>
    </p>
    <table id="articleList" class="table table-hover">
        <thead style="background-color:#bade61 ">

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.article_name)
                </th>

                @*<th>
                    @Html.DisplayNameFor(model => model.date_time)
                </th>*@
                @*<th>
                    @Html.DisplayNameFor(model => model.rating)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.expert_email)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.article_name)
                    </td>

                    @*<td>
                            @Html.DisplayFor(modelItem => item.date_time)
                        </td>*@
                    @*<td>
                            @Html.DisplayFor(modelItem => item.rating)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.expert_email)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                    </td>
                </tr>
            }
        </tbody>
    </table>



    @section Scripts {
        <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
        <script>
            $(document).ready(function () {
                
                $('#articleList').DataTable({
                    "order": [[3, "desc"]]
                });
            })

            $("#createArticle").on('click', function () {
                //ajax request
                $.ajax({
                    url: '/articles/create',
                    type: 'get'
                }).done(function (data) {
                    $("#modalBody").html(data);
                    $("#myModalLabel").html("Article - Create");
                    $('#myModal').modal('show');
                }).fail(function (err) {
                    alert(err);
                });
            });

        </script>
    }

    </div>

Agroin4/Views/articles/message.cshtml
@{
    ViewBag.Title = "Unsuccessful";
}



@if (TempData["testmsg"] != null)
{
    @Html.Raw(TempData["testmsg"])
}

@*<div>
    @Html.ActionLink("Back ", "Index")
</div>*@