Agroin4/Models/crop.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Agroin4.Models
{
    public class crop
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Crop name is required")]
        [Display(Name = "Crop Name")]

        public string crop_name { get; set; }
       // [Required(ErrorMessage = "Description is required")]

       
        [Required(ErrorMessage = "Topography is required")]
        [Display(Name = "Topography Name")]


        public int topography_id { get; set; }
        
        [ForeignKey ("topography_id")]
        public virtual topography topographys { get; set; }
        //  [Required(ErrorMessage = "Season is required")]
        [Display(Name = "Season Name")]

        public int season_id { get; set; }
        [ForeignKey("season_id")]

        public virtual seasondef Season { get; set; }
    }

    public class CropViewModel
    {
        public int id { get; set; }
        [Display(Name = "Crop Name")]
        public string crop_name { get; set; }
        [Display(Name = "Topography Name")]

        public int topography_id { get; set; }
        [Display(Name = "Topography Name")]
        public string topography_Name { get; set; }

        public int season_id { get; set; }
        [Display(Name = "Season Name")]
        public string season_Name { get; set; }

    }

}

Agroin4/Controllers/cropsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Agroin4.Models;

namespace Agroin4.Controllers
{
    public class cropsController : Controller
    {
        private webAppModel db = new webAppModel();
        public ActionResult Moreinfo(int id)
        {
            return RedirectToAction("Index","articles", new { Id= id});
        }
        // GET: crops
        public ActionResult Index()
        {
            var cropVM = db.crops.Select(p => new CropViewModel() { crop_name = p.crop_name, id = p.id, season_id = p.season_id, topography_id = p.topography_id, topography_Name = p.topographys.topography_name, season_Name = p.Season.season_name });
        
            return View(cropVM);
        }

        // GET: crops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            crop crop = db.crops.Find(id);
            if (crop == null)
            {
                return HttpNotFound();
            }
            return View(crop);
        }
        [Authorize(Roles = "Admin")]

        // GET: crops/Create
        public ActionResult Create()
        {
            ViewData["IdSeasonList"] = db.seasondefs.Select(p => new SelectListItem() { Text = p.season_name, Value = p.id.ToString() }).AsEnumerable();
            ViewData["IdTopographyList"] = db.topographys.Select(p => new SelectListItem() { Text = p.topography_name, Value = p.id.ToString() }).AsEnumerable();
            //ViewBag.topography_id = new SelectList(db.topographys, "id", "topography_name");
            return PartialView();
        }

        // POST: crops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( crop crop)
        {
            if (ModelState.IsValid)
            {
                db.crops.Add(crop);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           // ViewBag.topography_id = new SelectList(db.topographys, "id", "topography_name", crop.topography_id);
            return PartialView(crop);
        }
        [Authorize(Roles = "Admin")]

        // GET: crops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewData["IdSeasonList"] = db.seasondefs.Select(p => new SelectListItem() { Text = p.season_name, Value = p.id.ToString() }).AsEnumerable();
            ViewData["IdTopographyList"] = db.topographys.Select(p => new SelectListItem() { Text = p.topography_name, Value = p.id.ToString() }).AsEnumerable();
            crop crop = db.crops.Find(id);
            if (crop == null)
            {
                return HttpNotFound();
            }
           // ViewBag.topography_id = new SelectList(db.topographys, "id", "topography_name", crop.topography_id);
            return View(crop);
        }

        // POST: crops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,crop_name,topography_id,season_id")] crop crop)
        {
            if (ModelState.IsValid)
            {
                db.Entry(crop).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.topography_id = new SelectList(db.topographys, "id", "topography_name", crop.topography_id);
            return View(crop);
        }
        [Authorize(Roles = "Admin")]

        // GET: crops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            crop crop = db.crops.Find(id);
            if (crop == null)
            {
                return HttpNotFound();
            }
            return View(crop);
        }

        // POST: crops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            crop crop = db.crops.Find(id);
            db.crops.Remove(crop);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Agroin4/Views/crops/Create.cshtml
@model Agroin4.Models.crop

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>crop</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.crop_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 p-b-10">
                @Html.EditorFor(model => model.crop_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.crop_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.topography_id, "topography_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 p-b-10">
                @Html.DropDownList("topography_id", ViewData["IdTopographyList"] as IEnumerable<SelectListItem>, "Select Topography", htmlAttributes: new { @class = "form-control" })

                
                @Html.ValidationMessageFor(model => model.topography_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.season_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 p-b-10">
                @Html.DropDownList("season_id", ViewData["IdSeasonList"] as IEnumerable<SelectListItem>, "Select Season", htmlAttributes: new { @class = "form-control" })

                
                @Html.ValidationMessageFor(model => model.season_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

Agroin4/Views/crops/Delete.cshtml
@model Agroin4.Models.crop

@{
    ViewBag.Title = "Delete";
}

@*<h2>Delete</h2>*@
<div class="card">

    
    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Are you sure you want to delete this?</h2>
    </div>
    <div>
        @*<h4>crop</h4>*@
        @*<hr />*@
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.topographys.topography_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.topographys.topography_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.crop_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.crop_name)
            </dd>

            @*<dt>
                    @Html.DisplayNameFor(model => model.season_id)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.season_id)
                </dd>*@

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Agroin4/Views/crops/Details.cshtml
@model Agroin4.Models.crop

@{
    ViewBag.Title = "Details";
}

@*<h2>Details</h2>*@

<div>
    @*<h4>crop</h4>*@
    @*<hr />*@
    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Crop Details</h2>
    </div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.topographys.topography_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.topographys.topography_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.crop_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.crop_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.season_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.season_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Agroin4/Views/crops/Edit.cshtml
@model Agroin4.Models.crop

@{
    ViewBag.Title = "Edit";
}

@*<h2>Edit</h2>*@
<div class="card">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            
            <div class="header bg-light-green">
                <h2 class="col-light-green p-l-10 ">Edit</h2>
            </div>
            @*<hr />*@
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.crop_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6 p-b-10 p-t-10">
                    @Html.EditorFor(model => model.crop_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.crop_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.topography_id, "topography_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6 p-b-10">
                    @Html.DropDownList("topography_id", ViewData["IdTopographyList"] as IEnumerable<SelectListItem>, "Select Topography", htmlAttributes: new { @class = "form-control" })


                    @Html.ValidationMessageFor(model => model.topography_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.season_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6 p-b-10">
                    @Html.DropDownList("season_id", ViewData["IdSeasonList"] as IEnumerable<SelectListItem>, "Select Season", htmlAttributes: new { @class = "form-control" })


                    @Html.ValidationMessageFor(model => model.season_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
            
        </div>
    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    
</div>

Agroin4/Views/crops/Index.cshtml
@model IEnumerable<Agroin4.Models.CropViewModel>

@{
    ViewBag.Title = "Index";
}

<div class="card">
    
    <div class="header bg-light-green">
        <h2 class="col-light-green p-l-10 ">Index</h2>
    </div>
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <p>
        <button type="button" class="btn btn-primary" id="createCrop"><span class="glyphicon glyphicon-plus "></span></button>
        @*@Html.ActionLink("Create New", "Create","crops")*@

    </p>

    <table id="cropList" class="table table-hover">
        <thead style="background-color:#bade61 "  >

            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.crop_name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.topography_Name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.season_Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.crop_name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.topography_Name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.season_Name)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                        @*@Html.ActionLink("Details", "Details", new { id = item.id }) |*@
                        @Html.ActionLink("Moreinfo", "Moreinfo", new { id = item.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @section Scripts {
        <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    
        <script>
            $(document).ready(function () {
                $('#cropList').DataTable({
                    "order": [[3, "desc"]]
                });
            })
            $("#createCrop").on('click', function () {
                //ajax request
                $.ajax({
                    url: '/crops/create',
                    type: 'get'
                }).done(function (data) {
                    $("#modalBody").html(data);
                    $("#myModalLabel").html("Crop - Create");
                    $('#myModal').modal('show');
                }).fail(function (err) {
                    alert(err);
                });
            });
        </script>
   
    }
</div>